apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: ftor
spec:
  type: ClusterIP
  selector:
    app: model-serving
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
